version: "0.5"

processes:
  db:
    command: start-postgres-app
    ready_log_line: "is ready to accept connections"
  caddy:
    command: caddy run --config Caddyfile --adapter caddyfile
  backend:
    command: cd services/backend && uv run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ready_log_line: "Application startup complete."
    depends_on:
      db:
        condition: process_log_ready
  db-explorer:
    command: pgweb --url postgres://datata1:devpassword@localhost:5432/umwelt --skip-open --prefix=db-admin
    depends_on:
      backend:
        condition: process_log_ready
  frontend:
    command: cd services/frontend/app/ && uv run python app.py
    depends_on:
      db:
        condition: process_log_ready
  prefect:
    command: prefect server start
    ready_log_line: "Check out the dashboard at http://127.0.0.1:4200"
    depends_on:
      db:
        condition: process_log_ready
    environment:
      - PREFECT_SERVER_API_DATABASE_CONNECTION_URL=${PREFECT_SERVER_API_DATABASE_CONNECTION_URL}
      - PREFECT_API_URL=${PREFECT_API_URL} 
      - PREFECT_UI_SERVE_BASE=${PREFECT_UI_SERVE_BASE}
      - PREFECT_SERVER_DATABASE_CONNECTION_URL=${PREFECT_SERVER_DATABASE_CONNECTION_URL}
  prefect-worker:
    command: chmod +x ./services/ml_service/utils/prefect_worker.sh &&  cd ./services/ml_service && ./utils/prefect_worker.sh
    depends_on:
      db:
        condition: process_log_ready
    replicas: 1
  redis:
    command: redis-server
    depends_on:
      db:
        condition: process_log_ready
  